<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\OrderStatus;
use App\Enums\FulfillmentStatus;
use App\Models\Order;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Order>
 */
final class OrderFactory extends Factory
{
    protected $model = Order::class;

    public function definition(): array
    {
        $name = fake()->name();
        $status = fake()->randomElement(OrderStatus::cases());
        $fulfillment = match ($status) {
            OrderStatus::Delivered, OrderStatus::Shipped => FulfillmentStatus::Fulfilled,
            OrderStatus::Processing => fake()->randomElement([FulfillmentStatus::Unfulfilled, FulfillmentStatus::Partial]),
            default => FulfillmentStatus::Unfulfilled,
        };
        $placedAt = fake()->dateTimeBetween('-4 months', 'now');

        return [
            // order_number is auto-generated by the model's creating hook (uses the store prefix).
            'user_id' => null,
            'status' => $status->value,
            'fulfillment_status' => $fulfillment->value,
            'customer_name' => $name,
            'customer_email' => fake()->safeEmail(),
            'customer_phone' => fake()->optional()->numerify('0## ### ####'),
            'shipping_address' => fake()->streetAddress(),
            'shipping_city' => fake()->city(),
            'shipping_zip' => fake()->postcode(),
            'shipping_country' => 'US',
            // Money is recomputed once details are attached (see recalcTotals()).
            'subtotal' => 0,
            'discount_total' => 0,
            'shipping_total' => 0,
            'tax_total' => 0,
            'grand_total' => 0,
            'shipping_method' => fake()->randomElement(['standard', 'express', 'pickup']),
            'carrier' => $fulfillment !== FulfillmentStatus::Unfulfilled ? fake()->randomElement(['DHL', 'FedEx', 'UPS', 'Local Courier']) : null,
            'tracking_number' => $fulfillment !== FulfillmentStatus::Unfulfilled ? strtoupper(fake()->bothify('TRK-####-????')) : null,
            'shipped_at' => $fulfillment !== FulfillmentStatus::Unfulfilled ? $placedAt : null,
            'fulfilled_at' => $fulfillment === FulfillmentStatus::Fulfilled ? $placedAt : null,
            'payment_method' => fake()->randomElement(['card', 'cod']),
            'paid_at' => in_array($status, [OrderStatus::Paid, OrderStatus::Processing, OrderStatus::Shipped, OrderStatus::Delivered, OrderStatus::Refunded], true)
                ? $placedAt
                : null,
            'placed_at' => $placedAt,
        ];
    }

    /** Force a specific status. */
    public function status(OrderStatus $status): static
    {
        return $this->state(fn () => ['status' => $status->value]);
    }
}
